server:
  port: 8081
  host: localhost
  servlet:
    context-path: /UserMicroService

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_micro_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: mail.restosys.co.uk
    port: 587
    username: info@restosys.co.uk
    password: JayBhole@Krupa11
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect